name: CD
on:
  push:
    branches: [ main ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set lower case owner name 
      id: vars
      run: echo "owner_lc=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    
    - name: Login to GHCR
      run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      run: |
        IMAGE="ghcr.io/${{ steps.vars.outputs.owner_lc }}/python-app:latest"
        docker build -t $IMAGE .
        docker push $IMAGE
  
